services:

  php:
    build:
      context: .
      dockerfile: docker/php/dev.Dockerfile
    working_dir: /udacity_sl_automation
    volumes:
      - ./:/var/www
      - ./vendor:/udacity_sl_automation/vendor/
      - ./data/logs/nginx:/var/log/nginx/
    ports:
      - 80:80